# https://github.com/influxdata/telegraf/tree/release-1.37/plugins/inputs/internet_speed
[[inputs.internet_speed]]
  name_prefix = "telegraf_"
  interval = "7h"
  memory_saving_mode = false
  cache = false
  connections = 0
  test_mode = "single"
  server_id_include = [
    "2916", # FORWEB, Lodz, Poland
    "3702", # LNET, Lodz, Poland
    "7720", # STK TV-SAT 364, Lodz, Poland
    "338",  # Exatel S.A, Warsaw, Poland
    "5326", # Internet Union S.A., Wroclaw, Poland
    "1958", # Compower - Detron, Krakow, Poland
  ]
