# https://github.com/influxdata/telegraf/tree/release-1.38/plugins/inputs/internet_speed
[[inputs.internet_speed]]
  name_prefix = "telegraf_"
  interval = "7h"
  memory_saving_mode = false
  cache = false
  connections = 2
  test_mode = "multi"
