{
 "title": "shelly_gen2_ht",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "postgres" },
   {
    "name": "ht_device_name",
    "query": "select distinct device_name from shelly_gen2_temperature where $__timeFilter(timestamp) and device_name is not null"
   },
   {
    "name": "bat_metric",
    "query": "device_id, device_id+device_name : device_id\\,'_'\\,device_name"
   }
  ]
 },
 "panels": [
  { "title": "temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "current temperature",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    max(tC) as tC,\n    cast(0 as timestamp) as time\nfrom (\n    select last(tC) as tC, device_name\n    from shelly_gen2_temperature\n    where device_name in ($ht_device_name) and $__timeFilter(timestamp)\n)"
    }
   ]
  },
  {
   "title": "temperature measurements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select \n    timestamp as time,\n    avg(tC) as tC,\n    device_name as metric\nfrom\n    shelly_gen2_temperature\nwhere\n    device_name in ($ht_device_name)\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  { "title": "humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "current humidity",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    max(rh),\n    cast(0 as timestamp) as time\nfrom (\n    select last(rh) as rh, device_name\n    from shelly_gen2_humidity\n    where device_name in ($ht_device_name) and $__timeFilter(timestamp)\n)"
    }
   ]
  },
  {
   "title": "humidity measurements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select \n    timestamp as time,\n    avg(rh) as rh,\n    device_name as metric\nfrom\n    shelly_gen2_humidity\nwhere\n    device_name in ($ht_device_name)\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  { "title": "device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "current battery value",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select min(battery_percent), cast(0 as timestamp) as time\nfrom (\n    select last(battery_percent) as battery_percent, device_name\n    from shelly_gen2_devicepower\n    where device_name in ($ht_device_name) and $__timeFilter(timestamp)\n)"
    }
   ]
  },
  {
   "title": "battery value/voltage measurements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select \n    timestamp as time,\n    avg(battery_V) as battery_V,\n    concat('bat_voltage_', ${bat_metric:raw}) as metric\nfrom\n    shelly_gen2_devicepower\nwhere\n    device_id in (\n        select \n            distinct device_id\n        from\n            shelly_gen2_humidity\n        where\n            device_name in ($ht_device_name)\n            and $__timeFilter(timestamp)\n    )\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "rawSql": "select \n    timestamp as time,\n    avg(bat_voltage) as bat_voltage,\n    concat('bat_voltage_', ${bat_metric:raw}) as metric\nfrom\n    shelly_ht_meter1\nwhere\n    device_id in (\n        select \n            distinct device_id\n        from\n            shelly_ht_meter1\n        where\n            device_name in ($ht_device_name)\n            and device_id is not null\n            and is_valid = true\n            and $__timeFilter(timestamp)\n    )\n    and is_valid = true\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "current battery voltage",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select min(battery_V), cast(0 as timestamp) time\nfrom (\n    select last(battery_V) as battery_V, device_name\n    from shelly_gen2_devicepower\n    where device_name in ($ht_device_name) and $__timeFilter(timestamp)\n)"
    }
   ]
  }
 ]
}