{
 "title": "mixed_aio",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "postgres" },
   { "name": "min_interval", "query": "1m, 2m, 5m, 30m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "livingroom temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "with livingroom_t as (\n    select device_id\n    from shelly_gen2_temperature\n    where device_name LIKE '%livingroom' and $__timeFilter(timestamp)\n)\n\nselect \n    $__time(timestamp),\n    avg(tC),\n    left(concat(device_name, '-', device_id), 24) as metric\nfrom\n    shelly_gen2_temperature\nwhere\n    (\n        (device_name like '%livingroom%')\n        or (device_id in (select device_id from livingroom_t) and device_id = device_name)\n    )\n    and idx = '0'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "with livingroom_t as (\n    select ieee_address\n    from zigbee2mqtt_shelly_bluhtdisplayzb\n    where friendly_name LIKE '%livingroom' and $__timeFilter(timestamp)\n)\n\nselect \n    $__time(timestamp),\n    avg(temperature),\n    left(concat(friendly_name, ieee_address), 24) as metric\nfrom\n    zigbee2mqtt_shelly_bluhtdisplayzb\nwhere\n    (\n        (friendly_name like '%livingroom%')\n        or (ieee_address in (select ieee_address from livingroom_t) and ieee_address = friendly_name)\n    )\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "with livingroom_t as (\n    select ieee_address\n    from zigbee2mqtt_shelly_sbht103c\n    where friendly_name LIKE '%livingroom' and $__timeFilter(timestamp)\n)\n\nselect \n    $__time(timestamp),\n    avg(temperature),\n    left(concat(friendly_name, ieee_address), 24) as metric\nfrom\n    zigbee2mqtt_shelly_sbht103c\nwhere\n    (\n        (friendly_name like '%livingroom%')\n        or (ieee_address in (select ieee_address from livingroom_t) and ieee_address = friendly_name)\n    )\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "with livingroom_t as (\n    select device_id\n    from shelly_gen2_blutrv\n    where device_name LIKE '%livingroom' and $__timeFilter(timestamp)\n)\n\nselect \n    $__time(timestamp),\n    avg(current_C),\n    left(concat(device_name, device_id), 24) as metric\nfrom\n    shelly_gen2_blutrv\nwhere\n    (\n        (device_name like '%livingroom%')\n        or (device_id in (select device_id from livingroom_t) and device_id = device_name)\n    )\n    and idx = '200'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)\n"
    },
    {
     "dataset": "qdb",
     "rawSql": "with livingroom_t as (\n    select device_id\n    from shelly_gen2_blutrv\n    where device_name LIKE '%livingroom' and $__timeFilter(timestamp)\n)\n\nselect \n    $__time(timestamp),\n    avg(target_C),\n    concat(left(concat(device_name, device_id), 20), '-targetC') as metric\nfrom\n    shelly_gen2_blutrv\nwhere\n    (\n        (device_name like '%livingroom%')\n        or (device_id in (select device_id from livingroom_t) and device_id = device_name)\n    )\n    and idx = '200'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)\n"
    },
    {
     "dataset": "qdb",
     "rawSql": "with livingroom_t as (\n    select device_id\n    from shelly_gen2_blutrv\n    where device_name LIKE '%livingroom%' and $__timeFilter(timestamp)\n)\n\nselect \n    $__time(timestamp),\n    avg(pos),\n    concat(left(concat(device_name, device_id), 20), '-pos') as metric\nfrom\n    shelly_gen2_blutrv\nwhere\n    (\n        (device_name like '%livingroom%')\n        or (device_id in (select device_id from livingroom_t) and device_id = device_name)\n    )\n    and idx = '200'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)\n"
    }
   ]
  },
  {
   "title": "livingroom humidities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "with livingroom_t as (\n    select device_id\n    from shelly_gen2_humidity\n    where device_name LIKE '%livingroom' and $__timeFilter(timestamp)\n)\n\nselect \n    $__time(timestamp),\n    avg(rh),\n    left(concat(device_name, '-', device_id), 24) as metric\nfrom\n    shelly_gen2_humidity\nwhere\n    (\n        (device_name like '%livingroom')\n        or (device_id in (select device_id from livingroom_t) and device_id = device_name)\n    )\n    and idx = '0'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "with livingroom_t as (\n    select ieee_address\n    from zigbee2mqtt_shelly_bluhtdisplayzb\n    where friendly_name LIKE '%livingroom' and $__timeFilter(timestamp)\n)\n\nselect \n    $__time(timestamp),\n    avg(humidity),\n    left(concat(friendly_name, ieee_address), 24) as metric\nfrom\n    zigbee2mqtt_shelly_bluhtdisplayzb\nwhere\n    (\n        (friendly_name like '%livingroom')\n        or (ieee_address in (select ieee_address from livingroom_t) and ieee_address = friendly_name)\n    )\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "with livingroom_t as (\n    select ieee_address\n    from zigbee2mqtt_shelly_sbht103c\n    where friendly_name LIKE '%livingroom' and $__timeFilter(timestamp)\n)\n\nselect \n    $__time(timestamp),\n    avg(humidity),\n    left(concat(friendly_name, ieee_address), 24) as metric\nfrom\n    zigbee2mqtt_shelly_sbht103c\nwhere\n    (\n        (friendly_name like '%livingroom')\n        or (ieee_address in (select ieee_address from livingroom_t) and ieee_address = friendly_name)\n    )\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "with livingroom_t as (\n    select ieee_address\n    from zigbee2mqtt_sonoff_snzb02wd\n    where friendly_name LIKE '%livingroom' and $__timeFilter(timestamp)\n)\n\nselect \n    $__time(timestamp),\n    avg(humidity),\n    left(concat(friendly_name, ieee_address), 24) as metric\nfrom\n    zigbee2mqtt_sonoff_snzb02wd\nwhere\n    (\n        (friendly_name like '%livingroom')\n        or (ieee_address in (select ieee_address from livingroom_t) and ieee_address = friendly_name)\n    )\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "various temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(tC) as tC,\n    device_name as metric\nfrom\n    shelly_gen2_temperature\nwhere\n    device_name not like '%outdoor%' \n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "select \n    $__time(timestamp),\n    avg(temperature) as temperature,\n    friendly_name as metric\nfrom\n    zigbee2mqtt_shelly_bluhtdisplayzb\nwhere\n    friendly_name not like '%outdoor%' \n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "select \n    $__time(timestamp),\n    avg(temperature) as temperature,\n    friendly_name as metric\nfrom\n    zigbee2mqtt_sonoff_snzb02wd\nwhere\n    friendly_name not like '%outdoor%' \n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "select \n    $__time(timestamp),\n    avg(temperature) as temperature,\n    friendly_name as metric\nfrom\n    zigbee2mqtt_sonoff_snzb02p\nwhere\n    friendly_name not like '%outdoor%' \n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "various humidities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(rh) as rh,\n    device_name as metric\nfrom\n    shelly_gen2_humidity\nwhere\n    device_name not like '%outdoor%' \n    AND $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "select \n    $__time(timestamp),\n    avg(humidity) as humidity,\n    friendly_name as metric\nfrom\n    zigbee2mqtt_shelly_bluhtdisplayzb\nwhere\n    friendly_name not like '%outdoor%' \n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "select \n    $__time(timestamp),\n    avg(humidity) as humidity,\n    friendly_name as metric\nfrom\n    zigbee2mqtt_sonoff_snzb02wd\nwhere\n    friendly_name not like '%outdoor%' \n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "select \n    $__time(timestamp),\n    avg(humidity) as humidity,\n    friendly_name as metric\nfrom\n    zigbee2mqtt_sonoff_snzb02p\nwhere\n    friendly_name not like '%outdoor%' \n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "wattmeters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(apower) as apower,\n    device_name as metric\nfrom\n    shelly_gen2_switch\nwhere\n    $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "select \n    $__time(timestamp),\n    avg(power) as power,\n    friendly_name as metric\nfrom\n    zigbee2mqtt_sonoff_s60zbtpf\nwhere\n    $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "total power consumption",
   "type": "table",
   "description": "total for a given time range",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "dataset": "qdb",
     "rawSql": "WITH\nshelly_gen2_switch_b AS (\n    SELECT\n        timestamp AS ts,\n        device_name,\n        apower,\n        lag(timestamp) OVER (PARTITION BY device_name ORDER BY timestamp) AS prev_ts,\n    FROM shelly_gen2_switch\n    WHERE $__timeFilter(timestamp)\n)\nSELECT\n    $__time(0),\n    device_name,\n    sum(apower*(datediff('u', ts, prev_ts)))/(3600.0*1000000) as value\nFROM shelly_gen2_switch_b\nWHERE prev_ts IS NOT NULL\nGROUP by device_name"
    },
    {
     "rawSql": "WITH\nzigbee2mqtt_sonoff_s60zbtpf_b AS (\n    SELECT\n        timestamp AS ts,\n        friendly_name,\n        power,\n        lag(timestamp) OVER (PARTITION BY friendly_name ORDER BY timestamp) AS prev_ts,\n    FROM zigbee2mqtt_sonoff_s60zbtpf\n    WHERE $__timeFilter(timestamp)\n)\nSELECT\n    $__time(0),\n    friendly_name as device_name,\n    sum(power*(datediff('u', ts, prev_ts)))/(3600.0*1000000) as value\nFROM zigbee2mqtt_sonoff_s60zbtpf_b\nWHERE prev_ts IS NOT NULL\nGROUP by friendly_name"
    }
   ]
  },
  {
   "title": "outdoort tC&rh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(tC) as tC,\n    device_name as metric\nfrom\n    shelly_gen2_temperature\nwhere\n    device_name like '%outdoor%' \n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(rh) as rh,\n    concat(device_name, '-rh') as metric\nfrom\n    shelly_gen2_humidity\nwhere\n    device_name like '%outdoor%' \n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "select \n    $__time(timestamp),\n    avg(temperature) as temperature,\n    friendly_name as metric\nfrom\n    zigbee2mqtt_sonoff_snzb02wd\nwhere\n    friendly_name like '%outdoor%' \n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "select \n    $__time(timestamp),\n    avg(humidity) as humidity,\n    concat(friendly_name, '-rh') as metric\nfrom\n    zigbee2mqtt_sonoff_snzb02wd\nwhere\n    friendly_name like '%outdoor%' \n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "select \n    $__time(timestamp),\n    avg(temperature) as temperature,\n    friendly_name as metric\nfrom\n    zigbee2mqtt_shelly_bluhtdisplayzb\nwhere\n    friendly_name like '%outdoor%' \n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "dataset": "qdb",
     "rawSql": "select \n    $__time(timestamp),\n    avg(humidity) as humidity,\n    concat(friendly_name, '-rh') as metric\nfrom\n    zigbee2mqtt_shelly_bluhtdisplayzb\nwhere\n    friendly_name like '%outdoor%' \n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "battery states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(battery_percent) as battery_percent,\n    concat(device_name, '-', device_id) as metric\nfrom\n    shelly_gen2_devicepower\nwhere\n    $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(battery) as battery,\n    concat(friendly_name, '-', ieee_address) as metric\nfrom\n    zigbee2mqtt_shelly_bluhtdisplayzb\nwhere\n    $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(battery) as battery,\n    concat(friendly_name, '-', ieee_address) as metric\nfrom\n    zigbee2mqtt_sonoff_snzb02wd\nwhere\n    $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(battery) as battery,\n    concat(friendly_name, '-', ieee_address) as metric\nfrom\n    zigbee2mqtt_sonoff_snzb02p\nwhere\n    $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "speedtest",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(download) as download,\n    avg(upload) as upload\nfrom\n    telegraf_internet_speed\nwhere\n    $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  }
 ]
}