{
 "title": "shelly_ht_meter1",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "postgres" },
   {
    "name": "ht_device_name",
    "query": "select distinct device_name from shelly_ht_meter1 where $__timeFilter(timestamp) and device_name is not null\n"
   },
   {
    "name": "bat_metric",
    "query": "device_id, device_id+device_name : device_id\\,'_'\\,device_name"
   }
  ]
 },
 "panels": [
  { "title": "temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "current temperature",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    max(tmp_tc) as tmp_tc,\n    cast(0 as timestamp) as time\nfrom (\n    select last(tmp_tc) as tmp_tc, device_name\n    from shelly_ht_meter1\n    where device_name in ($ht_device_name) and is_valid = true and tmp_is_valid = true and $__timeFilter(timestamp)\n)\n"
    }
   ]
  },
  {
   "title": "temperature measurements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select \n    timestamp as time,\n    avg(tmp_tc) as tmp_tc,\n    device_name as metric\nfrom\n    shelly_ht_meter1\nwhere\n    device_name in ($ht_device_name)\n    and is_valid = true\n    and tmp_is_valid = true\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "temperature measurement failure rate",
   "type": "gauge",
   "description": "percentage of (is_valid=false or tmp_is_valid=false)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with\n    shelly_ht_meter1b as (\n        select timestamp, is_valid, tmp_is_valid\n        from shelly_ht_meter1\n        where device_name in ($ht_device_name) and $__timeFilter(timestamp)\n    ),\n    count_all as (\n        select count() as value\n        from shelly_ht_meter1b\n    ),\n    count_not_valid as (\n        select count() as value\n        from shelly_ht_meter1b\n        where is_valid = false or tmp_is_valid = false\n    )\nselect \n    cast(0 as timestamp) time,\n    ((1.0*count_not_valid.value)/count_all.value) as value\nfrom count_all\ncross join count_not_valid"
    }
   ]
  },
  { "title": "humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "current humidity",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    max(hum_value),\n    cast(0 as timestamp) as time\nfrom (\n    select last(hum_value) as hum_value, device_name\n    from shelly_ht_meter1\n    where device_name in ($ht_device_name) and is_valid = true and hum_is_valid = true and $__timeFilter(timestamp)\n)"
    }
   ]
  },
  {
   "title": "humidity measurements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select \n    timestamp as time,\n    avg(hum_value) as hum_value,\n    device_name as metric\nfrom\n    shelly_ht_meter1\nwhere\n    device_name in ($ht_device_name)\n    and is_valid = true\n    and hum_is_valid = true\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "humidity measurement failure rate",
   "type": "gauge",
   "description": "percentage of (is_valid=false or tmp_is_valid=false)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with\n    shelly_ht_meter1b as (\n        select timestamp, is_valid, hum_is_valid\n        from 'shelly_ht_meter1'\n        where device_name in ($ht_device_name) and $__timeFilter(timestamp)\n    ),\n    count_all as (\n        select count() as value\n        from shelly_ht_meter1b\n    ),\n    count_not_valid as (\n        select count() as value\n        from shelly_ht_meter1b\n        where is_valid = false or hum_is_valid = false\n    )\nselect \n    cast(0 as timestamp) time,\n    ((1.0*count_not_valid.value)/count_all.value) as value\nfrom count_all\ncross join count_not_valid"
    }
   ]
  },
  { "title": "device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "current battery value",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select min(bat_value), cast(0 as timestamp) as time\nfrom (\n    select last(bat_value) as bat_value, device_name\n    from shelly_ht_meter1\n    where device_name in ($ht_device_name) and is_valid = true and $__timeFilter(timestamp)\n)"
    }
   ]
  },
  {
   "title": "battery value/voltage measurements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select \n    timestamp as time,\n    avg(bat_value) as bat_value,\n    concat('bat_value_', ${bat_metric:raw}) as metric\nfrom\n    shelly_ht_meter1\nwhere\n    device_id in (\n        select \n            distinct device_id\n        from\n            shelly_ht_meter1\n        where\n            device_name in ($ht_device_name)\n            and device_id is not null\n            and is_valid = true\n            and $__timeFilter(timestamp)\n    )\n    and is_valid = true\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "rawSql": "select \n    timestamp as time,\n    avg(bat_voltage) as bat_voltage,\n    concat('bat_voltage_', ${bat_metric:raw}) as metric\nfrom\n    shelly_ht_meter1\nwhere\n    device_id in (\n        select \n            distinct device_id\n        from\n            shelly_ht_meter1\n        where\n            device_name in ($ht_device_name)\n            and device_id is not null\n            and is_valid = true\n            and $__timeFilter(timestamp)\n    )\n    and is_valid = true\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "current sensor_error",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    sum(sensor_error) as sensor_error,\n    cast(0 as timestamp) as time\nfrom (\n    select last(sensor_error) as sensor_error, device_name\n    from shelly_ht_meter1\n    where device_name in ($ht_device_name) and is_valid = true and $__timeFilter(timestamp)\n)"
    }
   ]
  },
  {
   "title": "current battery voltage",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select min(bat_voltage), cast(0 as timestamp) time\nfrom (\n    select last(bat_voltage) as bat_voltage, device_name\n    from shelly_ht_meter1\n    where device_name in ($ht_device_name) and is_valid = true and $__timeFilter(timestamp)\n)"
    }
   ]
  },
  {
   "title": "current connect_retries",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    sum(connect_retries) as connect_retries,\n    cast(0 as timestamp) as time\nfrom\n(\n    select last(connect_retries) as connect_retries, device_name\n    from shelly_ht_meter1\n    where device_name in ($ht_device_name) and is_valid = true and $__timeFilter(timestamp)\n)"
    }
   ]
  }
 ]
}