{
 "title": "shelly_gen2_temperature",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "postgres" },
   {
    "name": "device_name",
    "query": "select distinct device_name from shelly_gen2_temperature where $__timeFilter(timestamp)"
   },
   {
    "name": "device_id",
    "query": "select distinct device_id from shelly_gen2_temperature where device_name = '$device_name' and $__timeFilter(timestamp)"
   },
   {
    "name": "idx",
    "query": "select distinct idx from shelly_gen2_temperature where device_id = '$device_id' and $__timeFilter(timestamp)"
   },
   {
    "name": "filter",
    "query": "device_id : device_id = '$device_id' and idx = '$idx', device_name : device_name = '$device_name' and idx = '$idx', device_name+device_id : device_name = '$device_name' and device_id = '$device_id' and idx = '$idx'"
   }
  ]
 },
 "panels": [
  { "title": "temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "current temperature",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(0), last(tC)\nfrom shelly_gen2_temperature\nwhere ${filter:raw} and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "temperature measurements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(tC) as tC,\n    device_name as metric\nfrom\n    shelly_gen2_temperature\nwhere\n    ${filter:raw}\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  { "title": "humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "current humidity",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(0), last(rh)\nfrom shelly_gen2_humidity\nwhere ${filter:raw} and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "humidity measurements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(rh) as rh,\n    device_name as metric\nfrom\n    shelly_gen2_humidity\nwhere\n    ${filter:raw}\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  { "title": "device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "current battery value",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(0), last(battery_percent)\nfrom shelly_gen2_devicepower\nwhere device_id = '$device_id' and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "battery value/voltage measurements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(battery_percent) as battery_percent,\n    concat('bat_value_', device_id) as metric\nfrom\n    shelly_gen2_devicepower\nwhere\n    device_id = '$device_id'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(battery_V) as battery_V,\n    concat('bat_voltage_', device_id) as metric\nfrom\n    shelly_gen2_devicepower\nwhere\n    device_id = '$device_id'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "current battery voltage",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(0), last(battery_V)\nfrom shelly_gen2_devicepower\nwhere device_id = '$device_id' and $__timeFilter(timestamp)\n"
    }
   ]
  }
 ]
}