{
 "title": "zigbee2mqtt_temperatures",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "postgres" },
   {
    "name": "table_name",
    "query": "zigbee2mqtt_sonoff_snzb02wd, zigbee2mqtt_sonoff_snzb02p, zigbee2mqtt_shelly_bluhtdisplayzb, zigbee2mqtt_shelly_sbht103c"
   },
   {
    "name": "friendly_name",
    "query": "select distinct friendly_name from $table_name where $__timeFilter(timestamp)"
   },
   {
    "name": "ieee_address",
    "query": "select distinct ieee_address from $table_name where friendly_name = '$friendly_name' and $__timeFilter(timestamp)"
   },
   {
    "name": "filter",
    "label": "filter_device",
    "query": "ieee_address : ieee_address = '$ieee_address', \nfriendly_name : friendly_name = '$friendly_name',\nfriendly_name+ieee_address : ((friendly_name = '$friendly_name') or (ieee_address = '$ieee_address' and ieee_address = friendly_name)) "
   }
  ]
 },
 "panels": [
  { "title": "temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "current temperature",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(0), last(temperature)\nfrom $table_name\nwhere ${filter:raw} and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "temperature measurements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(temperature) as temperature,\n    friendly_name as metric\nfrom\n    $table_name\nwhere\n    ${filter:raw}\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  { "title": "humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "current humidity",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(0), last(humidity)\nfrom $table_name\nwhere ${filter:raw} and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "humidity measurements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(humidity) as humidity,\n    friendly_name as metric\nfrom\n    $table_name\nwhere\n     ${filter:raw}\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  { "title": "battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "current battery value",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(0), last(battery)\nfrom $table_name\nwhere ieee_address = '$ieee_address' and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "battery value/voltage measurements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(battery) as battery,\n    concat('bat_value_', ieee_address) as metric\nfrom\n    $table_name\nwhere\n    ieee_address = '$ieee_address'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(COALESCE(voltage, 0))/1000 as voltage,\n    concat('bat_voltage_', ieee_address) as metric\nfrom\n    $table_name\nwhere\n    ieee_address = '$ieee_address'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "current battery voltage",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(0), last(voltage)/1000\nfrom $table_name\nwhere ieee_address = '$ieee_address' and $__timeFilter(timestamp)"
    }
   ]
  },
  { "title": "device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "current linkquality value",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(0), last(linkquality)\nfrom $table_name\nwhere ieee_address = '$ieee_address' and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "linkquality",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(linkquality) as linkquality,\n    ieee_address as metric,\nfrom\n    $table_name\nwhere\n    ieee_address = '$ieee_address'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  }
 ]
}