{
 "title": "zigbee2mqtt_plugs",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "postgres" },
   { "name": "table_name", "query": "zigbee2mqtt_sonoff_s60zbtpf" },
   {
    "name": "friendly_name",
    "query": "select distinct friendly_name from $table_name where $__timeFilter(timestamp)\n"
   },
   {
    "name": "ieee_address",
    "query": "select distinct ieee_address from $table_name where friendly_name = '$friendly_name' and $__timeFilter(timestamp)"
   },
   {
    "name": "filter",
    "label": "filter_device",
    "query": "ieee_address : ieee_address = '$ieee_address', \nfriendly_name : friendly_name = '$friendly_name',\nfriendly_name+ieee_address : ((friendly_name = '$friendly_name') or (ieee_address = '$ieee_address' and ieee_address = friendly_name)) "
   },
   { "name": "interval", "label": "consumption interval", "query": "1m,2m,10m,30m,1h,1d,7d,30d" }
  ]
 },
 "panels": [
  { "title": "light panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "current power",
   "type": "gauge",
   "description": "last measurement",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(0), last(power)\nfrom $table_name\nwhere ${filter:raw} and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "total power consumption (broken?)",
   "type": "stat",
   "description": "total for a given time range",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with\n    data_t as (\n        select timestamp, energy, ieee_address\n        from $table_name\n        where ${filter:raw} and $__timeFilter(timestamp)\n    ),\n    consumption_t as (\n        select (case when t1.energy >= t2.energy then t1.energy-t2.energy else null end) as consumption\n        from data_t t1\n        lt join data_t t2\n        on t1.ieee_address = t2.ieee_address\n    )\nselect\n    $__time(0),\n    sum(consumption)*1000 as value -- kWh to Wh\nfrom consumption_t"
    }
   ]
  },
  {
   "title": "power consumption ",
   "type": "timeseries",
   "description": "sampled by \"consumption interval\"",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "with\n    data_t as (\n        SELECT\n            timestamp AS ts,\n            lag(timestamp) OVER (PARTITION BY ieee_address ORDER BY timestamp) AS prev_ts,\n            power,\n        FROM $table_name\n        WHERE ${filter:raw} and $__timeFilter(timestamp)\n    ),\n    interval_s as (\n        select (case\n            when '$interval' like '%s' then cast(left('$interval', -1) as int)*1\n            when '$interval' like '%m' then cast(left('$interval', -1) as int)*60\n            when '$interval' like '%h' then cast(left('$interval', -1) as int)*3600\n            when '$interval' like '%d' then cast(left('$interval', -1) as int)*86400\n            when '$interval' like '%w' then cast(left('$interval', -1) as int)*604800\n            when '$interval' like '%M' then cast(left('$interval', -1) as int)*2678400\n            when '$interval' like '%y' then cast(left('$interval', -1) as int)*31536000\n            else 0 end\n        ) as value\n    ),\n    consumption_t as (\n        (\n            select\n                t1.ts,\n                sum(t1.power*(datediff('u', t1.ts, t1.prev_ts)))/(3600.0*1000000) as consumption\n            from data_t t1\n            cross join interval_s\n            where datediff('s', t1.ts, t1.prev_ts) <= interval_s.value\n        ) timestamp(ts)\n    )\nselect\n    $__time(ts),\n    sum(consumption) as value\nfrom consumption_t\nsample by $interval fill(null) align to calendar"
    }
   ]
  },
  {
   "title": "total power consumption",
   "type": "stat",
   "description": "total for a given time range",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH\nzigbee2mqtt_sonoff_s60zbtpf_b AS (\n    SELECT\n        timestamp AS ts,\n        power,\n        lag(timestamp) OVER (PARTITION BY ieee_address ORDER BY timestamp) AS prev_ts,\n    FROM zigbee2mqtt_sonoff_s60zbtpf\n    WHERE ${filter:raw} and $__timeFilter(timestamp)\n)\nSELECT\n    $__time(0),\n    sum(power*(datediff('u', ts, prev_ts)))/(3600.0*1000000) as value\nFROM zigbee2mqtt_sonoff_s60zbtpf_b\nWHERE prev_ts IS NOT NULL"
    }
   ]
  },
  {
   "title": "wattmeter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(power) as power\nfrom $table_name\nwhere\n    ${filter:raw}\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "linkquality",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(linkquality) as linkquality,\n    ieee_address as metric,\nfrom\n    $table_name\nwhere\n    ${filter:raw}\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  { "title": "light panels extra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "ammeter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(current) as current\nfrom $table_name\nwhere\n    ${filter:raw}\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "voltmeter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(voltage) as voltage\nfrom $table_name\nwhere\n    ${filter:raw}\n    and $__timeFilter(timestamp)\n    and voltage > 0\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "powerfactor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(power) as apower,\n    avg(voltage)*avg(current) as apparent_power,\n    avg(power)/(avg(voltage)*avg(current)) as pf\nfrom $table_name\nwhere\n    ${filter:raw}\n    and $__timeFilter(timestamp)\n    and voltage>0\nsample by $__interval fill(null)"
    }
   ]
  }
 ]
}