{
 "title": "zigbee2mqtt_sonoff_snzb02wd",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "postgres" },
   {
    "name": "friendly_name",
    "query": "select distinct friendly_name from zigbee2mqtt_sonoff_snzb02wd where $__timeFilter(timestamp)"
   },
   {
    "name": "ieee_address",
    "query": "select distinct ieee_address from zigbee2mqtt_sonoff_snzb02wd where friendly_name = '$friendly_name' and $__timeFilter(timestamp)"
   },
   {
    "name": "filter",
    "query": " ieee_address : ieee_address = '$ieee_address',  friendly_name : friendly_name = '$friendly_name', friendly_name+ieee_address : friendly_name = '$friendly_name' and ieee_address = '$ieee_address'"
   }
  ]
 },
 "panels": [
  { "title": "temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "current temperature",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(0), last(temperature)\nfrom zigbee2mqtt_sonoff_snzb02wd\nwhere ${filter:raw} and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "temperature measurements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(temperature) as temperature,\n    friendly_name as metric\nfrom\n    zigbee2mqtt_sonoff_snzb02wd\nwhere\n    ${filter:raw}\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  { "title": "humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "current humidity",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(0), last(humidity)\nfrom zigbee2mqtt_sonoff_snzb02wd\nwhere ${filter:raw} and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "humidity measurements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(humidity) as humidity,\n    friendly_name as metric\nfrom\n    zigbee2mqtt_sonoff_snzb02wd\nwhere\n     ${filter:raw}\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  { "title": "device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "current battery value",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(0), last(battery)\nfrom zigbee2mqtt_sonoff_snzb02wd\nwhere ieee_address = '$ieee_address' and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "battery value/voltage measurements",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(battery) as battery,\n    concat('bat_value_', ieee_address) as metric\nfrom\n    zigbee2mqtt_sonoff_snzb02wd\nwhere\n    ieee_address = '$ieee_address'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    },
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(voltage)/1000 as voltage,\n    concat('bat_voltage_', ieee_address) as metric\nfrom\n    zigbee2mqtt_sonoff_snzb02wd\nwhere\n    ieee_address = '$ieee_address'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "current battery voltage",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__time(0), last(voltage)/1000\nfrom zigbee2mqtt_sonoff_snzb02wd\nwhere ieee_address = '$ieee_address' and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "linkquality",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select \n    $__time(timestamp),\n    avg(linkquality) as linkquality,\n    ieee_address as metric,\nfrom\n    zigbee2mqtt_sonoff_snzb02wd\nwhere\n    ieee_address = '$ieee_address'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  }
 ]
}